# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dddc997ed7ab108941217c89afeceb295b4f23a7b31a179c2fbbdd0f3c8c8ec8b06be12ab7f34165b9d7fd2bf26d0df2379ebdc7d09a9a9d2fd559388e6dcfa2

test:
  secret_key_base: f8d4472a0e0a4595153f820881d7b3b427f86d63f25918902fb6c89882d32265139a1facaa43fb43fee1fa1a2a1f38b875b3a1668577f055e0a9d8a1cc25d86f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
